version: 2
jobs:

  build.NET:
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore backend
      - run: dotnet build backend
      # - run: dotnet test src/Sample.Tests
  
  build-Angular:
    working_directory: ~/REST-CSharp/ClientApp
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: npm run ng -- build --prod --aot --no-progress
      - run:
          name: angular-test
          command: npm run test -- --single-run --no-progress
      - store_artifacts:
          path: test-results.xml
          prefix: tests
